[bumpver]
current_version = "v0.1.2"
version_pattern = "vMAJOR.MINOR.PATCH"
commit_message = "chore: [skip build] bump version {old_version_pep440} -> {new_version_pep440}"
tag_message = "release {new_version_pep440}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = false

[bumpver.file_patterns]
"plugin-build/buildSrc/src/main/java/Maven.kt" = [
    'const val VERSION = "{pep440_version}"',
]
"README.md" = [
    'id("jp.co.gahojin.refreshVersions") version "{pep440_version}"'
]
"example/settings.gradle.kts" = [
    'id("jp.co.gahojin.refreshVersions") version "{pep440_version}"'
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
