/*
 * (C) 2025 GAHOJIN, Inc.
 */
package jp.co.gahojin.refreshVersions.internal

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class VersionCatalogCleanerTest : StringSpec({
    "空" {
        VersionCatalogCleaner.execute("".reader(), sortSection = false) shouldBe ""
    }

    "Generated Byなし" {
        VersionCatalogCleaner.execute("""
            |[plugins]
            |hoge = "1.0.0"
            |""".trimMargin().reader(), sortSection = false) shouldBe """
                |## Generated by $ ./gradlew refreshVersions
                |
                |[plugins]
                |
                |hoge = "1.0.0"
                |""".trimMargin()
    }

    "改行が2行以上ある場合は1行になること & セクションの後は改行となること" {
        VersionCatalogCleaner.execute("""
            |## Generated by $ ./gradlew refreshVersions
            |
            |[plugins]
            |hoge = "1.0.0"
            |foo = "1.0.1"
            |
            |
            |boo = "2.0.0"
            |
            |boo2 = "1.0.0"
            |
            |
            |""".trimMargin().reader(), sortSection = false) shouldBe """
                |## Generated by $ ./gradlew refreshVersions
                |
                |[plugins]
                |
                |hoge = "1.0.0"
                |foo = "1.0.1"
                |
                |boo = "2.0.0"
                |
                |boo2 = "1.0.0"
                |""".trimMargin()
    }

    "バージョンコメントが削除されること" {
        VersionCatalogCleaner.execute("""
            |## Generated by $ ./gradlew refreshVersions
            |
            |[versions]
            |hoge = "1.0.0"
            |##     ^1.0.1
            |foo = "1.0.1"
            |
            |boo = "2.0.0"
            |##    ^2.0.1
            |##    ^3.0.0
            |
            |""".trimMargin().reader(), sortSection = false) shouldBe """
                |## Generated by $ ./gradlew refreshVersions
                |
                |[versions]
                |
                |hoge = "1.0.0"
                |foo = "1.0.1"
                |
                |boo = "2.0.0"
                |""".trimMargin()
    }

    "セクションソート確認" {
        VersionCatalogCleaner.execute("""
            |## Generated by $ ./gradlew refreshVersions
            |
            |[versions]
            |boo = "2.0.0"
            |boo2 = "1.0.0"
            |foo = "1.0.1"
            |hoge = "1.0.0"
            |
            |[plugins]
            |a = "a:1.0"
            |
            |[bundles]
            |b = "a:b:1.0"
            |
            |[libraries]
            |c = "c:d:1.0"
            |""".trimMargin().reader(), sortSection = true) shouldBe """
                |## Generated by $ ./gradlew refreshVersions
                |
                |[versions]
                |
                |boo = "2.0.0"
                |boo2 = "1.0.0"
                |foo = "1.0.1"
                |hoge = "1.0.0"
                |
                |[libraries]
                |
                |c = "c:d:1.0"
                |
                |[bundles]
                |
                |b = "a:b:1.0"
                |
                |[plugins]
                |
                |a = "a:1.0"
                |""".trimMargin()
    }

    "Generated byコメント追加確認" {
        VersionCatalogCleaner.execute("""
            |[versions]
            |boo = "2.0.0"
            |""".trimMargin().reader(), sortSection = true) shouldBe """
                |## Generated by $ ./gradlew refreshVersions
                |
                |[versions]
                |
                |boo = "2.0.0"
                |""".trimMargin()
    }

    "他のコメントがある場合、Generated byコメント追加されない" {
        VersionCatalogCleaner.execute("""
            |## テスト
            |
            |[versions]
            |boo = "2.0.0"
            |""".trimMargin().reader(), sortSection = true) shouldBe """
                |## テスト
                |
                |[versions]
                |
                |boo = "2.0.0"
                |""".trimMargin()
    }
})
