package jp.co.gahojin.refreshVersions

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class VersionCatalogCleanerTest : StringSpec({
    "空" {
        VersionCatalogCleaner.execute("".reader(), sortSection = false) shouldBe ""
    }

    "Generated Byなし" {
        VersionCatalogCleaner.execute("""
            |[plugins]
            |hoge = "1.0.0"
            |""".trimMargin().reader(), sortSection = false) shouldBe """
                |## Generated by $ ./gradlew refreshVersions
                |
                |[plugins]
                |
                |hoge = "1.0.0"
                |""".trimMargin()
    }

    "改行が2行以上ある場合は1行になること & セクションの後は改行となること" {
        VersionCatalogCleaner.execute("""
            |## Generated by $ ./gradlew refreshVersions
            |
            |[plugins]
            |hoge = "1.0.0"
            |foo = "1.0.1"
            |
            |
            |boo = "2.0.0"
            |
            |boo2 = "1.0.0"
            |
            |
            |""".trimMargin().reader(), sortSection = false) shouldBe """
                |## Generated by $ ./gradlew refreshVersions
                |
                |[plugins]
                |
                |hoge = "1.0.0"
                |foo = "1.0.1"
                |
                |boo = "2.0.0"
                |
                |boo2 = "1.0.0"
                |""".trimMargin()
    }

    "バージョンコメントが削除されること" {
        VersionCatalogCleaner.execute("""
            |## Generated by $ ./gradlew refreshVersions
            |
            |[plugins]
            |hoge = "1.0.0"
            |##     ^1.0.1
            |foo = "1.0.1"
            |
            |boo = "2.0.0"
            |##    ^2.0.1
            |##    ^3.0.0
            |
            |""".trimMargin().reader(), sortSection = false) shouldBe """
                |## Generated by $ ./gradlew refreshVersions
                |
                |[plugins]
                |
                |hoge = "1.0.0"
                |foo = "1.0.1"
                |
                |boo = "2.0.0"
                |""".trimMargin()
    }
})
